version: '2.2'
services:
  ums_web:
    build: ./server
    image: ums_web:v0.1
    container_name: ums_web_container
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    links:
      - ums_db
    tty: true
  ums_app:
    build: ./
    image: ums_app:v0.1
    container_name: ums_app_container
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    tty: true
  ums_db:
    image: mongo
    container_name: ums_db_container
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    tty: true
